config/routes.rb
Rails.application.routes.draw do

  resources :offereds
  resources :wanteds
  devise_for :users
  resources :games
  resources :users

  get 'offereds/index'
  root 'offereds#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/rrootouting.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :offereds, dependent: :destroy
  has_many :users, through: :offereds
  has_many :wanteds, dependent: :destroy
  has_many :users, through: :wanteds
  validates :title, presence: :true, uniqueness: { case_sensitive: false }

end

app/models/offered.rb
class Offered < ApplicationRecord
  belongs_to :user
  belongs_to :game

end

app/models/user.rb
class User < ApplicationRecord
  has_many :offereds, dependent: :destroy
  has_many :users, through: :offereds
  has_many :wanteds, dependent: :destroy
  has_many :users, through: :wanteds
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-z0-9_]*$/, :multiline => true
  extend FriendlyId
  friendly_id :username, use: :slugged

end

app/models/wanted.rb
class Wanted < ApplicationRecord
  belongs_to :user
  belongs_to :game

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected

  def configure_permitted_parameters
    added_attrs = [:email,:username, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.where(["title LIKE ?","%#{params[:search]}%"])
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title)
    end
end

app/controllers/offereds_controller.rb
class OfferedsController < ApplicationController
  before_action :set_offered, only: [:show, :edit, :update, :destroy]

  # GET /offereds
  # GET /offereds.json
  def index
    @offereds = Offered.all
  end

  # GET /offereds/1
  # GET /offereds/1.json
  def show
  end

  # GET /offereds/new
  def new
    @offered = Offered.new
  end

  # GET /offereds/1/edit
  def edit
  end

  # POST /offereds
  # POST /offereds.json
  def create
    @offered = Offered.new(offered_params)

    respond_to do |format|
      if @offered.save
        format.html { redirect_to "/games", notice: 'Jogo adicionado a lista de ofertados' }
        format.json { render :show, status: :created, location: @offered }
      else
        format.html { render :new }
        format.json { render json: @offered.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offereds/1
  # PATCH/PUT /offereds/1.json
  def update
    respond_to do |format|
      if @offered.update(offered_params)
        format.html { redirect_to @offered, notice: 'Jogo atualizado aos ofertados com sucesso.' }
        format.json { render :show, status: :ok, location: @offered }
      else
        format.html { render :edit }
        format.json { render json: @offered.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offereds/1
  # DELETE /offereds/1.json
  def destroy
    @offered.destroy
    respond_to do |format|
      format.html { redirect_to "/users/" + current_user.username, notice: 'Jogo retirado da lista de ofertados' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offered
      @offered = Offered.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offered_params
      params.require(:offered).permit(:user_id, :game_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if user_signed_in? 
      @user = User.friendly.find(params[:id])
    else 
      redirect_to  new_user_session_path
    end
  end
  

end

app/controllers/wanteds_controller.rb
class WantedsController < ApplicationController
  before_action :set_wanted, only: [:show, :edit, :update, :destroy]

  # GET /wanteds
  # GET /wanteds.json
  def index
    @wanteds = Wanted.all
  end

  # GET /wanteds/1
  # GET /wanteds/1.json
  def show
  end

  # GET /wanteds/new
  def new
    @wanted = Wanted.new
  end

  # GET /wanteds/1/edit
  def edit
  end

  # POST /wanteds
  # POST /wanteds.json
  def create
    @wanted = Wanted.new(wanted_params)

    respond_to do |format|
      if @wanted.save
        format.html { redirect_to "/games", notice: 'Jogo adicionado a lista de desejos' }
        format.json { render :show, status: :created, location: @wanted }
      else
        format.html { render :new }
        format.json { render json: @wanted.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wanteds/1
  # PATCH/PUT /wanteds/1.json
  def update
    respond_to do |format|
      if @wanted.update(wanted_params)
        format.html { redirect_to "/games", notice: 'Wanted was successfully updated.' }
        format.json { render :show, status: :ok, location: @wanted }
      else
        format.html { render :edit }
        format.json { render json: @wanted.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wanteds/1
  # DELETE /wanteds/1.json
  def destroy
    @wanted.destroy
    respond_to do |format|
      format.html { redirect_to "/users/" + current_user.username, notice: 'Jogo removido a lista de desejos' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wanted
      @wanted = Wanted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wanted_params
      params.require(:wanted).permit(:user_id, :game_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/offereds_helper.rb
module OfferedsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wanteds_helper.rb
module WantedsHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class="field">
    <%= form.text_field :title %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit "Confirmar", class: "btn btn-primary" %>
  </div>
  <br>

<% end %>

app/views/games/edit.html.erb
<h1>Editando Jogo</h1>

<%= render 'form', game: @game %>

<%= link_to 'Voltar', games_path %>

app/views/games/index.html.erb
<font color="green"><p id="notice"><%= notice %></p></font>

<h1>Jogos</h1>

<%= form_tag games_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Buscar", class: "btn btn-secondary" %>
<% end %>
<br>

<% if (user_signed_in?) %>

  <% if (current_user.username == "admin_user") %>
    <td><%= link_to 'CRIAR JOGO', new_game_path, class: "btn btn-primary" %></td><br>
  <% end %>

<% end %>

<br>

<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <% if (user_signed_in?) %>
        <td><%= link_to 'Adicionar a lista de Oferecidos', new_offered_path(:param1 => game.id, :param2 => game.title), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Adicionar a lista de Desejos', new_wanted_path(:param1 => game.id, :param2 => game.title), class: "btn btn-secondary " %></td>
        

          <% if (current_user.username == "admin_user") %>
            <td><%= link_to 'EDITAR', edit_game_path(game), class: "btn btn-warning" %></td>
            <td><%= link_to 'DELETAR', game, method: :delete, data: { confirm: 'Tem Certeza?' }, class: "btn btn-danger" %></td>
          <% end %>

        <% else %>
          <td><%= link_to 'Adicionar a lista de Oferecidos', new_user_session_path, class: "btn btn-secondary" %></td>
          <td><%= link_to 'Adicionar a lista de Desejos', new_user_session_path, class: "btn btn-secondary" %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1>Novo Jogo</h1>

<%= render 'form', game: @game %>

<%= link_to 'Voltar', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameLink</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" >
  <a class="navbar-brand" href="/offereds"><font color="white"> GameLink </font></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/offereds"><font color="white"> Home </font><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/games"><font color="white"> Jogos </font><span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
    <% if user_signed_in? %>
      <% @user= current_user %>
        <%= link_to " Perfil ",  {controller: "users", action: "show", id: current_user.username}, class:"btn btn-secondary"  %>    
        &ensp;
        &ensp;
        <%= link_to " Logout ",  destroy_user_session_path, method: :DELETE , class: "btn btn-secondary" %>
      <%else%>
        <%= link_to " Cadastro ", new_user_registration_path , class: "btn btn-secondary"  %>
        &ensp;
        &ensp;
        <%= link_to " Login ",  new_user_session_path ,  class: "btn btn-secondary" %>
      <% end %>
    </form>
  </div>
</nav>
  <body>
    <div class= "container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/offereds/_form.html.erb
<%= form_with(model: offered, local: true) do |form| %>
  <% if offered.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offered.errors.count, "error") %> prohibited this offered from being saved:</h2>

      <ul>
        <% offered.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :user_id, value: current_user.id,:hidden => true%>
  </div>

  <div class="field">
    <%= form.text_field :game_id, value: params[:param1],:hidden => true  %>
  </div>

  <br>
  <h3>Adicionar <%= params[:param2] %> a sua lista de ofertados?</h3>

  <br>
  <div class="actions">
    <%= form.submit "Confirmar", class: "btn btn-secondary" %>
  </div>
  <br>

<% end %>

app/views/offereds/edit.html.erb
<h1>Editing Offered</h1>

<%= render 'form', offered: @offered %>

<%= link_to 'Show', @offered %> |
<%= link_to "Home",  {controller: "offereds", action: "index"}  %>

app/views/offereds/index.html.erb
<font color="green"><p id="notice"><%= notice %></p></font>

<p>
  <h1>
    Ofertados pela Comunidade
  </h1>
  <h5> 
    <%= link_to "Registrar Jogos no seu Perfil",  {controller: "games", action: "index"}  %>
  </h5>
</p>

<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Jogo Ofertado</th>
    </tr>
  </thead>

  <tbody>
    <% @offereds.each do |offered| %>
      <tr>
        <td><%= link_to offered.user.username ,{controller: "users", action: "show", id: offered.user.username} %></td>
        <td><%= offered.game.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h3></h3>

app/views/offereds/new.html.erb
<%= render 'form', offered: @offered %>

<%= link_to "Voltar",  {controller: "games", action: "index"}, class: "btn btn-secondary"  %>

app/views/offereds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @offered.user.username %>
</p>

<p>
  <strong>Game:</strong>
  <%= @offered.game.title %>
</p>

<%= link_to "Home",  {controller: "offereds", action: "index"}  %>

app/views/users/show.html.erb
<font color="green"><p id="notice"><%= notice %></p></font>

<% if user_signed_in? && current_user.username == @user.username %>
    <h1>
        Bem vindo, <%= current_user.username %>
    </h1>
    <body>
        <p>
            Email: <%= current_user.email%>
        </p>

        <p>
            Username: <%=current_user.username%>
        </p>

        <h2>Jogos Ofertados:</h2>

        <p>

          <table class="table table-striped table-dark">

            <tbody>
              <% @user.offereds.each do |offered| %>
                <tr>
                  <td><%= offered.game.title %></td>
                  <td><%= link_to 'Deletar', offered, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger" %></td>
                </tr>
              <% end %>
            </tbody>

          </table>

        </p>

        <h2>Jogos Desejados:</h2>

        <p>
          
            <table class="table table-striped table-dark">

              <tbody>
                <% @user.wanteds.each do |wanted| %>
                  <tr>
                    <td><%= wanted.game.title %></td>
                    <td><%= link_to 'Deletar', wanted, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger" %></td>
                  </tr>
                <% end %>
              </tbody>

            </table>
          
        </p>

<% else %>

    <h1>
        Bem vindo ao perfil do <%= @user.username %>
    </h1>
    <body>
        <p>
            Email: <%= @user.email%>
        </p>

        <h2>Jogos Ofertados:</h2>

        <p>
          <% @user.offereds.each do |offered| %>
              <%= offered.game.title %><br>
          <% end %>
        </p>

        <h2>Jogos Desejados:</h2>

        <p>
          <% @user.wanteds.each do |wanted| %>
              <%= wanted.game.title %><br>
          <% end %>
        </p>

    </body>
<% end %>

app/views/wanteds/_form.html.erb
<%= form_with(model: wanted, local: true) do |form| %>
  <% if wanted.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wanted.errors.count, "error") %> prohibited this wanted from being saved:</h2>

      <ul>
        <% wanted.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :user_id, value: current_user.id, :hidden => true %>
  </div>

  <div class="field">
    <%= form.text_field :game_id, value: params[:param1], :hidden => true%>
  </div>

  <br>
  <h3>Adicionar <%= params[:param2] %> a sua lista de desejos?</h3>
  
  <br>
  <div class="actions">
    <%= form.submit "Confirmar", class: "btn btn-secondary" %>
  </div>
  <br>

<% end %>

app/views/wanteds/edit.html.erb
<h1>Editing Wanted</h1>

<%= render 'form', wanted: @wanted %>

<%= link_to 'Show', @wanted %> |
<%= link_to 'Back', wanteds_path %>

app/views/wanteds/index.html.erb
<h1>Desejados</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wanteds.each do |wanted| %>
      <tr>
        <td><%= wanted.user_id %></td>
        <td><%= wanted.game_id %></td>
        <td><%= link_to 'Show', wanted %></td>
        <td><%= link_to 'Edit', edit_wanted_path(wanted) %></td>
        <td><%= link_to 'Destroy', wanted, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Home",  {controller: "offereds", action: "index"}  %>

app/views/wanteds/new.html.erb
<%= render 'form', wanted: @wanted %>

<%= link_to "Voltar",  {controller: "games", action: "index"}, class: "btn btn-secondary"  %>

app/views/wanteds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @wanted.user_id %>
</p>

<p>
  <strong>Game:</strong>
  <%= @wanted.game_id %>
</p>

<%= link_to 'Edit', edit_wanted_path(@wanted) %> |
<%= link_to 'Back', wanteds_path %>